apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-calculator-deployment
  labels:
    app: bmi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmi
  template:
    metadata:
      labels:
        app: bmi
    spec:
      containers:
        - name: bmi-calculator-container
          image: manoharshetty507/bmi-calculator-app:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: color-game-service
spec:
  type: NodePort
  selector:
    app: bmi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80